version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: dantemoren/diplom_frontend
    volumes:
      - ./frontend:/app/result_build/build/
      - redoc:/app/docs/

  web:
    image: dantemoren/diplom_backend
    container_name: web
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../forntend:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
  