# Generated by Django 3.2.9 on 2021-12-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_title_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите имя ингредиента', max_length=100)),
                ('measurement_unit', models.CharField(help_text='Укажите единицу измерения ингредиента', max_length=100)),
            ],
        ),
    ]
