# Generated by Django 3.2.9 on 2021-12-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20211208_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={},
        ),
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
    ]
