# Generated by Django 3.2.9 on 2021-12-13 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0017_auto_20211213_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorite_this',
            field=models.ManyToManyField(blank=True, related_name='favourite_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Кому понравилось'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='shopping_carts',
            field=models.ManyToManyField(blank=True, related_name='shopping_carts', to=settings.AUTH_USER_MODEL, verbose_name='Кто хочет купить'),
        ),
    ]
