# Generated by Django 3.2.9 on 2021-12-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20211213_0921'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
    ]
